imagePullPolicy: IfNotPresent

api:
  image: store-lab-api:0.1.0
  replicas: 2
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

worker:
  image: store-lab-api:0.1.0
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

web:
  image: store-lab-web:0.1.0
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

admin:
  image: store-lab-admin:0.1.0
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

goLoader:
  enabled: false
  image: app-go-loader:0.1.0
  replicas: 1
  users: 10
  orderPeriod: 1m
  minDelay: 5s
  maxDelay: 15s
  maxProductsPerOrder: 3
  userEmailDomain: load.example.com
  userPasswordSecretKey: GO_LOADER_USER_PASSWORD
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi

config:
  appName: Store Lab API
  appVersion: 0.1.0
  environment: production
  corsOrigins: '["http://store-lab-web","http://store-lab-admin"]'
  accessTokenExpireMinutes: "60"

secretRef:
  name: store-lab-secrets
