apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-lab.fullname" . }}-api
  labels:
    {{- include "store-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "store-lab.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ include "store-lab.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secretRef.name }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

