{{- if .Values.goLoader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-lab.fullname" . }}-go-loader
  labels:
    {{- include "store-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-loader
spec:
  replicas: {{ .Values.goLoader.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: go-loader
  template:
    metadata:
      labels:
        {{- include "store-lab.labels" . | nindent 8 }}
        app.kubernetes.io/component: go-loader
    spec:
      containers:
        - name: go-loader
          image: {{ .Values.goLoader.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "--users={{ .Values.goLoader.users }}"
          env:
            - name: API_BASE_URL
              value: http://{{ include "store-lab.fullname" . }}-api
            - name: ORDER_PERIOD
              value: {{ .Values.goLoader.orderPeriod | quote }}
            - name: MIN_DELAY
              value: {{ .Values.goLoader.minDelay | quote }}
            - name: MAX_DELAY
              value: {{ .Values.goLoader.maxDelay | quote }}
            - name: MAX_PRODUCTS_PER_ORDER
              value: {{ .Values.goLoader.maxProductsPerOrder | quote }}
            - name: USER_EMAIL_DOMAIN
              value: {{ .Values.goLoader.userEmailDomain | quote }}
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRef.name }}
                  key: {{ .Values.goLoader.userPasswordSecretKey }}
          resources:
            {{- toYaml .Values.goLoader.resources | nindent 12 }}
{{- end }}
