apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-lab.fullname" . }}-web
  labels:
    {{- include "store-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.web.port }}

