apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "store-lab.fullname" . }}-worker
  labels:
    {{- include "store-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "store-lab.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["celery", "-A", "app.worker.celery_app.celery_app", "worker", "--loglevel=INFO"]
          envFrom:
            - configMapRef:
                name: {{ include "store-lab.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secretRef.name }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}

